server:
  port: 8080
  max-http-header-size: 10000000

spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
    name:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '*19980424*'

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

qqlogin:
  #qq快速登录
  #主要
  call-back-url: 
  app-id: 
  app-key: 

  #开发测试
  #call-back-url: http://127.0.0.1:8080/qqlogin
  #app-id: 
  #app-key: 

  get-authorizaion-code: https://graph.qq.com/oauth2.0/authorize
  get-access-token: https://graph.qq.com/oauth2.0/token
  get-open-id: https://graph.qq.com/oauth2.0/me
  get-user-info: https://graph.qq.com/user/get_user_info

wps:
  #wps自动邀请
  wps-invite-url: https://zt.wps.cn/2018/clock_in/api/invite

head-image:
  #默认头像地址
  default-head-image: https://chairc.cn/pic/HeadImage/default/default-head.svg
  default-head-image-man: https://chairc.cn/pic/HeadImage/default/default-head-man.svg
  default-head-image-woman: https://chairc.cn/pic/HeadImage/default/default-head-woman.svg
